# SwiftLint Configuration for PiggyBong
  # Professional iOS app development standards

  # Include only relevant directories
  included:
    - FanPlan

  # Exclude generated and dependency files
  excluded:
    - Pods
    - DerivedData
    - OldFiles
    - .build
    - Package.swift
    - scripts

  # Only run rules on these file types
  file_types:
    - swift

  # Enabled rules for production-ready code
  opt_in_rules:
    - array_init
    - attributes
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - conditional_returns_on_newline
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - convenience_type
    - discouraged_object_literal
    - empty_count
    - empty_string
    - empty_xctest_method
    - explicit_init
    - fatal_error_message
    - file_header
    - first_where
    - force_unwrapping
    - function_default_parameter_at_end
    - identical_operands
    - implicit_return
    - joined_default_parameter
    - last_where
    - legacy_random
    - literal_expression_end_indentation
    - lower_acl_than_parent
    - modifier_order
    - multiline_arguments
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - operator_usage_whitespace
    - overridden_super_call
    - override_in_extension
    - pattern_matching_keywords
    - prefer_self_type_over_type_of_self
    - private_action
    - private_outlet
    - prohibited_super_call
    - quick_discouraged_call
    - quick_discouraged_focused_test
    - quick_discouraged_pending_test
    - reduce_into
    - redundant_nil_coalescing
    - redundant_type_annotation
    - required_enum_case
    - single_test_class
    - sorted_first_last
    - sorted_imports
    - strong_iboutlet
    - toggle_bool
    - trailing_closure
    - unneeded_parentheses_in_closure_argument
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - yoda_condition

  # Disabled rules that might be too strict for this project
  disabled_rules:
    - todo
    - line_length # Will be configured below
    - function_body_length # Will be configured below

  # Rule configurations
  line_length:
    warning: 120
    error: 150
    ignores_urls: true
    ignores_function_declarations: true
    ignores_comments: true

  file_length:
    warning: 400
    error: 500

  function_body_length:
    warning: 60
    error: 100

  function_parameter_count:
    warning: 6
    error: 8

  type_body_length:
    warning: 300
    error: 400

  large_tuple:
    warning: 3
    error: 4

  identifier_name:
    min_length:
      warning: 2
      error: 1
    max_length:
      warning: 50
      error: 60
    excluded:
      - id
      - url
      - URL
      - db
      - ui
      - vm

  nesting:
    type_level:
      warning: 3
      error: 4
    function_level:
      warning: 5
      error: 6

  cyclomatic_complexity:
    warning: 15
    error: 20

  # Custom rules for security and best practices
  custom_rules:
    no_hardcoded_secrets:
      name: "No Hardcoded Secrets"
      regex:
  '(?i)(password|secret|key|token)\s*=\s*["\'](?!\s*\$|\s*ProcessInfo|\s*Bundle|\s*your-)[^"\']+["\']'
      message: "Hardcoded secrets are not allowed. Use environment variables or secure storage."
      severity: error

    environment_variables_usage:
      name: "Use Environment Variables for Configuration"
      regex: 'static\s+let\s+\w*(url|key|secret|token)\w*\s*=\s*["\'][^"\']*["\']'
      message: "Use ProcessInfo.processInfo.environment for configuration values."
      severity: warning

    proper_error_handling:
      name: "Proper Error Handling"
      regex: 'try!\s+'
      message: "Avoid force try. Use proper error handling with do-catch."
      severity: warning

    secure_print_statements:
      name: "Secure Print Statements"
      regex: 'print\([^)]*(?:password|secret|key|token)[^)]*\)'
      message: "Don't print sensitive information. Use proper logging."
      severity: error

  # File header template (optional)
  file_header:
    required_pattern: |
                      \/\/
                      \/\/.*\.swift
                      \/\/.*PiggyBong
                      \/\/

  # Reporter configuration
  reporter: "github-actions-logging"

  # Analyzer rules (for more advanced checking)
  analyzer_rules:
    - explicit_self
    - unused_import
    - unused_declaration
