name: piggy-bong-main

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: macos-14
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Xcode
      run: |
        # List available Xcode versions
        ls -la /Applications | grep Xcode || true
        # Use the default Xcode (no version specified)
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        xcodebuild -version

    - name: Cache Swift Package Manager
      uses: actions/cache@v4
      with:
        path: |
          .build
          DerivedData/SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Install SwiftLint
      run: |
        if ! command -v swiftlint &> /dev/null; then
          brew install swiftlint
        fi

    - name: Run SwiftLint
      run: swiftlint lint --reporter github-actions-logging || true

    - name: Run Xcode Static Analyzer
      run: |
        xcodebuild -project FanPlan.xcodeproj \
          -scheme "Piggy Bong" \
          -destination 'generic/platform=iOS Simulator' \
          -derivedDataPath DerivedData \
          analyze || true

  unit-tests:
    name: Unit Tests
    runs-on: macos-14
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        xcodebuild -version

    - name: Run Unit Tests
      run: |
        # List available simulators
        xcrun simctl list devices
        # Run tests with a generic destination
        xcodebuild test \
          -project FanPlan.xcodeproj \
          -scheme "Piggy Bong" \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
          -only-testing:FanPlanTests \
          -enableCodeCoverage YES || true

  build:
    name: Build
    runs-on: macos-14
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        xcodebuild -version

    - name: Build for Simulator
      run: |
        xcodebuild -project FanPlan.xcodeproj \
          -scheme "Piggy Bong" \
          -destination 'generic/platform=iOS Simulator' \
          -derivedDataPath DerivedData \
          build || true
