import Foundation

print("🍎 APPLE SIGN-IN CONFIGURATION CHECK")
print(String(repeating: "=", count: 50))

// 1. Check Info.plist configuration
if let plistPath = Bundle.main.path(forResource: "Info", ofType: "plist"),
   let plistData = FileManager.default.contents(atPath: plistPath),
   let plist = try? PropertyListSerialization.propertyList(from: plistData, options: [], format: nil) as? [String: Any] {

    // Check Apple Client ID
    if let appleClientId = plist["APPLE_CLIENT_ID"] as? String {
        print("✅ APPLE_CLIENT_ID: \(appleClientId)")
        if appleClientId == "carmenwong.PiggyBong.auth" {
            print("✅ Apple Client ID format is correct")
        } else {
            print("⚠️  Apple Client ID should be: carmenwong.PiggyBong.auth")
        }
    } else {
        print("❌ APPLE_CLIENT_ID not found in Info.plist")
    }

    // Check Bundle Identifier
    if let bundleId = plist["CFBundleIdentifier"] as? String {
        print("✅ Bundle Identifier: \(bundleId)")
        if bundleId == "carmenwong.PiggyBong" {
            print("✅ Bundle ID matches expected format")
        }
    }

    // Check URL Schemes for Apple Sign-In
    if let urlTypes = plist["CFBundleURLTypes"] as? [[String: Any]] {
        var foundAppleScheme = false

        for urlType in urlTypes {
            if let schemes = urlType["CFBundleURLSchemes"] as? [String] {
                for scheme in schemes {
                    if scheme.contains("carmenwong.PiggyBong") {
                        print("✅ Found Apple URL scheme: \(scheme)")
                        foundAppleScheme = true
                    }
                }
            }
        }

        if !foundAppleScheme {
            print("⚠️  Apple Sign-In URL scheme not found")
        }
    }

} else {
    print("❌ Could not load Info.plist")
}

print("\n" + String(repeating: "=", count: 50))
print("🔧 APPLE SIGN-IN SETUP REQUIREMENTS:")
print(String(repeating: "=", count: 50))

print("""

📋 CHECKLIST FOR APPLE SIGN-IN:

1️⃣  XCODE PROJECT SETTINGS:
   □ Open your project in Xcode
   □ Select your target (Piggy Bong)
   □ Go to "Signing & Capabilities" tab
   □ Click "+ Capability"
   □ Add "Sign In with Apple"

2️⃣  APPLE DEVELOPER ACCOUNT:
   □ Go to developer.apple.com
   □ Navigate to "Certificates, Identifiers & Profiles"
   □ Select your App ID (carmenwong.PiggyBong)
   □ Enable "Sign In with Apple" capability
   □ Configure if needed and save

3️⃣  SUPABASE DASHBOARD SETUP:
   □ Go to Supabase Dashboard > Authentication > Providers
   □ Enable "Apple" provider
   □ Client ID: carmenwong.PiggyBong.auth
   □ Secret: (Generated by Supabase automatically)
   □ Redirect URL: https://lxnenbhkmdvjsmnripax.supabase.co/auth/v1/callback

4️⃣  TESTING:
   □ Apple Sign-In ONLY works on:
     - Physical iOS device (iPhone/iPad)
     - NOT in iOS Simulator
   □ Must be signed in to iCloud on the device
   □ Must have two-factor authentication enabled

⚠️  IMPORTANT NOTES:
   • Apple Sign-In will NOT work in the iOS Simulator
   • You MUST test on a real device
   • The device must be signed into iCloud
   • Your Apple Developer account must be valid

""")

print(String(repeating: "=", count: 50))
print("✨ Apple Sign-In configuration check complete!")
print(String(repeating: "=", count: 50))